From 47f1e49917b7f738641a02138b76c5efa822d791 Mon Sep 17 00:00:00 2001
From: Jeroen Demeyer <jdemeyer@cage.ugent.be>
Date: Thu, 9 Jul 2015 23:05:19 +0200
Subject: [PATCH] Update NTL to 9.3.0

diff --git a/src/sage/libs/ntl/error.pyx b/src/sage/libs/ntl/error.pyx
index 64aedf4..bf8ea17 100644
--- a/src/sage/libs/ntl/error.pyx
+++ b/src/sage/libs/ntl/error.pyx
@@ -4,6 +4,9 @@ NTL error handler
 AUTHOR:
 
 - Jeroen Demeyer (2015-02-15): initial version, see :trac:`17784`
+
+- Jeroen Demeyer (2015-07-09): use standard NTL ``ErrorMsgCallback``,
+  see :trac:`18875`
 """
 
 #*****************************************************************************
@@ -18,8 +21,8 @@ AUTHOR:
 
 
 include "sage/ext/interrupt.pxi"
-from ntl_tools cimport SetErrorCallbackFunction
-from cpython.exc cimport PyErr_SetString
+from ntl_tools cimport ErrorMsgCallback
+
 
 class NTLError(RuntimeError):
     """
@@ -34,9 +37,10 @@ class NTLError(RuntimeError):
         NTLError: DivRem: division by zero
     """
 
-cdef void NTL_error_callback(const char* s, void* context):
-    PyErr_SetString(NTLError, s)
-    sig_error()
+
+cdef void NTL_error_callback(const char* s) except *:
+    raise NTLError(s)
+
 
 def setup_NTL_error_callback():
     """
@@ -47,4 +51,5 @@ def setup_NTL_error_callback():
         sage: from sage.libs.ntl.error import setup_NTL_error_callback
         sage: setup_NTL_error_callback()
     """
-    SetErrorCallbackFunction(NTL_error_callback, NULL)
+    global ErrorMsgCallback
+    ErrorMsgCallback = NTL_error_callback
diff --git a/src/sage/libs/ntl/ntl_tools.pxd b/src/sage/libs/ntl/ntl_tools.pxd
index 096e878..3cb8c05 100644
--- a/src/sage/libs/ntl/ntl_tools.pxd
+++ b/src/sage/libs/ntl/ntl_tools.pxd
@@ -1,2 +1,2 @@
 cdef extern from "NTL/tools.h" namespace "NTL":
-    void SetErrorCallbackFunction(void (*func)(const char *s, void *context), void *context)
+    void (*ErrorMsgCallback)(const char *) except *
